spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:apistore}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # update, create, or none
  
  flyway:
    enabled: true
    locations: classpath:db/migration
  
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant-path-matcher
  
  web:
    resources:
      add-mappings: false

# JWT Configuration
#jwt:
#  public:
#    key: classpath:app.pub
#  private:
#    key: classpath:app.key

# Server Configuration (uncomment and modify as needed)
#server:
#  port: ${SERVER_PORT:8080}
#  servlet:
#    context-path: /api

# Logging Configuration (uncomment and modify as needed)
#logging:
#  file:
#    name: logs/log-file.log
#  level:
#    root: INFO
#    org.springframework: INFO
#    br.com.asoft: DEBUG
