spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # será sobrescrito nos profiles específicos

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant-path-matcher

  web:
    resources:
      add-mappings: false