spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # Poder ser sobrescrito nos profiles específicos

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant-path-matcher

  web:
    resources:
      add-mappings: false

#Acima, fica as configurações comuns para todos os profiles 'dev' e 'prod'.