spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:apistore}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

# Variavel de Ambiente para o token JWT producao ou denvolvimento
app:
  environment: dev

#  jpa:
#    hibernate:
#      ddl-auto: update # Sobrescreve o ddl-auto do profile geral
