spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
       ddl-auto: none # Mude para "create-drop" se for desenvolvimento

#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true # Adicione esta linha

#  mvc:
#    throw-exception-if-no-handler-found: true
#    pathmatch:
#      matching-strategy: ant-path-matcher
#
#  web:
#    resources:
#      add-mappings: false
