create table product (
   id serial not null,
   description varchar(100) not null,
   barcode varchar(100) not null,
   unit varchar(10) not null,
   quant bigint not null,
   quant_min_stock bigint not null,
   value_buy decimal(10,2),
   value_sell decimal(10,2),
   date_last_buy date,
   observation varchar(100),
   status varchar(10) not null,
   date_register date,
   date_update date,
   id_category bigint not null,
   id_supplier bigint not null,
   constraint product_pk primary key (id),
   constraint fk_category foreign key (id_category) references category(id),
   constraint fk_supplier foreign key (id_supplier) references supplier(id)
);